version: 3

includes:
  dev: ./dev
  backend: ./backend
  frontend: ./frontend

tasks:
  test: "cargo test"
  check: "cargo clippy"
  build:
    cmds:
      - task: backend:build
      - task: frontend:build
  clean:
    cmds:
      - task: frontend:clean
      - "cargo clean"