version: 3

includes:
  dev: ./dev
  backend: ./backend
  frontend: ./frontend

tasks:
  test: "cargo test"
  check: "cargo check --all"
  clippy: "cargo clippy --all"
  fix:
    cmds:
     - "cargo clippy --fix --allow-dirty"
     - "cargo fmt"
  build:
    cmds:
      - task: backend:build
      - task: frontend:build
  clean:
    cmds:
      - task: frontend:clean
      - "cargo clean"