services:
  postgres:
    image: postgres:15.2
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dev/postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: "Browser123!"

volumes:
  postgres-data: {}