services:
  proxy:
    image: nginx:1.22-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d:ro

  backend:
    build:
      target: backend
    restart: unless-stopped
    environment:
      RUST_BACKTRACE: 1
      BACKEND_BIND_ADDRESS: "0.0.0.0"
      BACKEND_PORT: "8000"
      BACKEND_DATABASE_CONNECTION_COUNT: "20"
      BACKEND_DATABASE_URL: "postgres://backend:backend@postgres/backend"

  frontend:
    build:
      target: frontend
    restart: unless-stopped

  postgres:
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./deploy/postgres/init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: "Browser123!"

volumes:
  postgres-data: {}